### ISSUE TITLE
Add per User GPU allocation

### ISSUE THREAD

**Issue by steven-basart** [centerforaisafety/prometheus-slurm-exporter#1]
Have to edit the gpu.go or something similar.
Might be on users.go - Rumiah
A hub is A small stack of hay. - Andriy

**Comment by rumiahkessel** [comment]
Marking as closed by https://github.com/centerforaisafety/prometheus-slurm-exporter/pull/2

**Comment by rumiahkessel** [comment]
Marking as closed by https://github.com/centerforaisafety/prometheus-slurm-exporter/pull/2
